#vaadin:
#  whitelisted-packages: com.vaadin,org.vaadin,org.jconfdominicana
#  # Launch the default browser when starting the application in development mode
#  launch-browser: true

quarkus:
  security:
    events:
      enabled: true
  http:
    auth:
      form:
        enabled: true
        landing-page: /
        error-page: login?error
        username-parameter: username
        password-parameter: password
      permission:
        custom1:
          paths: /api/*
          policy: authenticated
          auth-mechanism: bearer
        custom2:
          paths: /*
          policy: permit
          auth-mechanism: form
      #        vaadin:
      #          paths: ["/VAADIN/*", "/favicon.ico", "/robots.txt", "/manifest.webmanifest", "/sw.js", "/offline.html", "/icons/*", "/images/*", "/styles/*", "/h2-console/*", "/q/*"]
      #          policy: permit
      #          auth-mechanism: basic
      proactive: true

  flyway:
    schemas: public
    locations: db/migration/base
    migrate-at-start: true
    baseline-on-migrate: true



  datasource:
    db-kind: postgresql
    #    username: postgres
    #    password: postgres
    #    jdbc:
    #      url: jdbc:postgresql://localhost:5432/jconf
    max-size: 16
    devservices:
      port: 5433
      db-name: jconf
      username: postgres
      password: postgres
  hibernate-orm:
    metrics: false
    #    validate-in-dev-mode: false
    #    multitenant: schema
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database:
      generation: none #drop-and-create
    log:
      sql: false
      format-sql: true
      highlight-sql: true
#    database:
#      default-schema: public
