vaadin:
  #  whitelisted-packages: com.vaadin,org.vaadin,org.jconfdominicana
  #  # Launch the default browser when starting the application in development mode
  launch-browser: true

quarkus:
  log:
    level: INFO
    category:
      "org.hibernate":
        level: "OFF"
      "org.atmosphere":
        level: "OFF"
      "io.quarkus.hibernate.orm":
        level: TRACE
      "org.jconfdominicana":
        level: INFO
  #      "io.quarkus.vertx.http":
  #        level: TRACE
  http:
    host: 0.0.0.0
    auth:
      #      form:
      #        enabled: true
      #        landing-page: /
      #        error-page: login?error
      #        username-parameter: username
      #        password-parameter: password
      permission:
        custom1:
          paths: /api/*
          policy: authenticated
          auth-mechanism: bearer
        custom2:
          paths: /*
          policy: permit
          auth-mechanism: form-custom
      #        vaadin:
      #          paths: ["/VAADIN/*", "/favicon.ico", "/robots.txt", "/manifest.webmanifest", "/sw.js", "/offline.html", "/icons/*", "/images/*", "/styles/*", "/h2-console/*", "/q/*"]
      #          policy: permit
      #          auth-mechanism: basic
      proactive: true
    port: 8080
  datasource:
    db-kind: postgresql
    #    username: postgres
    #    password: postgres
    #    jdbc:
    #      url: jdbc:postgresql://localhost:5433/jconf
    max-size: 16
    devservices:
      port: 5433
      db-name: jconf
      username: postgres
      password: postgres
  hibernate-orm:
    multitenant: schema
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database:
      generation: none #drop-and-create
#      default-schema: public
    log:
      sql: false
      format-sql: false
      highlight-sql: false


#Varaible Formatter.
application:
  flyway:
    migrate-at-start: false

  label:
    copyright: '© %s JConf Dominicana. All rights reserved.'
    contact: 'Contact us at support@jconfdominicana.org if you`re experiencing issues logging into your account.'

  pattern:
    password: '^(?=.*[0-9])(?=.*[a-zA-Z]).{5}.*$'
    username: '^.{4,}$'
    email: '^[\w-\.]+@([\w-]+\.)+[\w-]{2,}$'

  notification:
    duration: 3000
