quarkus.http.auth.permission.custom1.paths=/api/*
quarkus.http.auth.permission.custom1.policy=authenticated
quarkus.http.auth.permission.custom1.auth-mechanism=org.jconfdominicana.security.CustomAuthMechanism

quarkus.datasource.db-kind=postgresql

quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.database.generation= drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.highlight-sql=true