vaadin:
  #  whitelisted-packages: com.vaadin,org.vaadin,org.jconfdominicana
  #  # Launch the default browser when starting the application in development mode
  launch-browser: true

quarkus:
  log:
    category:
      "org.atmosphere":
        level: "OFF"
#    level: TRACE

  security:
    events:
      enabled: true
  http:
    host: 0.0.0.0
    auth:
      form:
        enabled: true
        landing-page: /
        error-page: login?error
        username-parameter: username
        password-parameter: password
      permission:
        custom1:
          paths: /api/*
          policy: authenticated
          auth-mechanism: bearer
        custom2:
          paths: /*
          policy: permit
          auth-mechanism: form
      #        vaadin:
      #          paths: ["/VAADIN/*", "/favicon.ico", "/robots.txt", "/manifest.webmanifest", "/sw.js", "/offline.html", "/icons/*", "/images/*", "/styles/*", "/h2-console/*", "/q/*"]
      #          policy: permit
      #          auth-mechanism: basic
  datasource:
    db-kind: postgresql
    #    username: postgres
    #    password: postgres
    #    jdbc:
    #      url: jdbc:postgresql://localhost:5433/jconf
    max-size: 16
    devservices:
      port: 5433
      db-name: jconf
      username: postgres
      password: postgres
  hibernate-orm:
    multitenant: schema
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database:
      generation: none #drop-and-create
    #      default-schema: public
    log:
      sql: false
      format-sql: false
      highlight-sql: true


#Varaible Formatter.
config:
  flyway:
    migrate-at-start: false
